import BottomTabsItem from "./BottomTabsItem";

export const BottomTabsList: Array<BottomTabsItem> = [
  {
    icon: $r('app.media.menu'),
    iconSelected: $r('app.media.menu'),
    text: $r('app.string.linechart')
  },
  {
    icon: $r('app.media.linechart'),
    iconSelected: $r('app.media.linechart'),
    text: $r('app.string.menu')
  },
  {
    icon: $r('app.media.user'),
    iconSelected: $r('app.media.user'),
    text: $r('app.string.user')
  }
]